### ISSUE TITLE
Microservices / Microsolutions / Ideas Suggested through UX Brainstorming 

### ISSUE THREAD

**Issue by Drmicrosoft** [ANTS-COIN/platform#10]
**Issue :** Presenting Own Progress and Keep Motivated 
**Solution :** Through Landing Page .. 3 Cells in a Row to Describe Achievements , Learning Score , Money Earned

**Comment by NorhanZ** [comment]
**Issue:** Need a cooperative helpful community to support each other and mentor each other.
**Solution:** - Screening to all earners to make sure they have this quality.
                     -  Make helping others as something that they get an incentive for.
                     - Create some sort of mandatory interaction between earners like games that require help and offering support for other players in order to pass the current level to the next one.

**Comment by mansour91** [comment]
### **UX,UI tutuorial/review**
[UX Design Tutorial for Beginners
](https://www.youtube.com/watch?v=I0-vBdh4sZ8&t=1052s)[What is UI vs. UX Design? A Practical Example in Under 6 Minutes
](https://www.youtube.com/watch?v=TgqeRTwZvIo&t=12s)

**Comment by Drmicrosoft** [comment]
![Screenshot from 2020-08-24 11-41-36](https://user-images.githubusercontent.com/4147924/91031176-87be3700-e600-11ea-890f-5f73b8319bb1.png)
![Screenshot from 2020-08-24 11-42-27](https://user-images.githubusercontent.com/4147924/91031186-8987fa80-e600-11ea-90cb-48eb979ad851.png)
![Screenshot from 2020-08-24 11-42-42](https://user-images.githubusercontent.com/4147924/91031192-8a209100-e600-11ea-8e68-7dbcc4f057b6.png)
![Screenshot from 2020-08-24 11-42-47](https://user-images.githubusercontent.com/4147924/91031196-8ab92780-e600-11ea-955e-60f18769778f.png)
![Screenshot from 2020-08-24 11-42-54](https://user-images.githubusercontent.com/4147924/91031197-8bea5480-e600-11ea-94fb-bfdf6b86ba1f.png)
![Screenshot from 2020-08-24 11-43-06](https://user-images.githubusercontent.com/4147924/91031199-8c82eb00-e600-11ea-8c09-612cad22ecba.png)
![Screenshot from 2020-08-24 11-43-20](https://user-images.githubusercontent.com/4147924/91031203-8c82eb00-e600-11ea-811b-9282a985586e.png)
![Screenshot from 2020-08-24 11-43-26](https://user-images.githubusercontent.com/4147924/91031206-8d1b8180-e600-11ea-80e1-cf73b321d142.png)
![Screenshot from 2020-08-24 11-43-38](https://user-images.githubusercontent.com/4147924/91031209-8e4cae80-e600-11ea-9707-707258879691.png)
![Screenshot from 2020-08-24 11-43-44](https://user-images.githubusercontent.com/4147924/91031211-8e4cae80-e600-11ea-99bf-e5323304b3fd.png)
![Screenshot from 2020-08-24 11-46-42](https://user-images.githubusercontent.com/4147924/91031214-8f7ddb80-e600-11ea-989a-65496db5060b.png)
![Screenshot from 2020-08-24 11-46-49](https://user-images.githubusercontent.com/4147924/91031217-8f7ddb80-e600-11ea-857d-5450587fe80d.png)
![Screenshot from 2020-08-24 11-47-06](https://user-images.githubusercontent.com/4147924/91031219-90167200-e600-11ea-94bb-370337dda030.png)
![Screenshot from 2020-08-24 11-47-14](https://user-images.githubusercontent.com/4147924/91031221-90af0880-e600-11ea-910c-9c42f4a8a37b.png)
![Screenshot from 2020-08-24 11-47-18](https://user-images.githubusercontent.com/4147924/91031223-90af0880-e600-11ea-9d3f-4e569d93c77e.png)
![Screenshot from 2020-08-24 11-47-57](https://user-images.githubusercontent.com/4147924/91031226-91479f00-e600-11ea-8b07-5db7abb0c4ce.png)
![Screenshot from 2020-08-24 11-48-22](https://user-images.githubusercontent.com/4147924/91031230-9278cc00-e600-11ea-9c10-ad69fb0ef239.png)
@yousei4 Competitors

**Comment by Drmicrosoft** [comment]
https://usabilitygeek.com/easy-ways-gamify-your-ux/ 
@mansour91 @mansour91 @yousei4

**Comment by Drmicrosoft** [comment]
![Screenshot from 2020-08-24 13-17-34](https://user-images.githubusercontent.com/4147924/91156575-9706b880-e6c4-11ea-9a50-0aa49cb86608.png)


@yousei4
