### ISSUE TITLE
Development Team Discussion

### ISSUE THREAD

**Issue by Drmicrosoft** [ANTS-COIN/platform#20]
Hello Team I opened this issue to discuss with you about Tool that is suitable on Wordpress Called Tutor Learning Management System that will Make 90% of Work That we should Do .. 

It Has A
     **Intuitive course builder**
    **Unlimited courses and lessons**
    **Frontend student dashboard**
    **Video lessons**
    **Multiple video sources (self-hosted, YouTube, Vimeo, Embedded Video)**
    **Teacher profiles and panels**
    **Lesson management**
    **Course requirement & instruction**
    **Quizzes**
    **Earning & Commission Allocation**
    **Withdrawal Options**
    **Purchase History**
    Styling Options
    Course Widget
    **Teacher registration form**
    **Course review and rating system**
    **Q&A for students with course teacher**
    Video Poster (trailer/teaser)
    **Tracking course progress**
    **Course Difficulty Level**
    **Define Course Duration**
    Course Marketplace
    Add course requirement and instruction
    Quiz Timer
    Quiz Attempts
    Centralized Monetization Settings
    Spotlight Mode
    RTL Ready
    Page Builder Support
    Gutenberg compatible
    Content Security

Please Check it out In this Link [Tutor LMS ](https://wordpress.org/plugins/tutor/) 

If So we can all Shift to WordPress

**Comment by Mo-Hossary** [comment]
I love it! Great Find, 
 
I think we can go ahead and build the Learning Advisory on WordPress then we can integrate. 

Please proceed to work on WordPress if you see fit for this sprint. 

@MayElDardiry @aamhegazy

**Comment by aamhegazy** [comment]
What about testing it with the existing learning materials and ask team to try.. and build on their feedback

**Comment by Drmicrosoft** [comment]
**Documentation**
https://docs.themeum.com/tutor-lms/

**Comment by Drmicrosoft** [comment]
**Demo as pics** 

![Screenshot from 2020-08-24 18-23-38](https://user-images.githubusercontent.com/4147924/91071277-48abd800-e638-11ea-8cc4-4948c9943e70.png)
![Screenshot from 2020-08-24 18-23-43](https://user-images.githubusercontent.com/4147924/91071283-49dd0500-e638-11ea-9503-eb2358f4f0a7.png)
![Screenshot from 2020-08-24 18-23-53](https://user-images.githubusercontent.com/4147924/91071286-4a759b80-e638-11ea-8c17-6d9e9b3f7cdd.png)
![Screenshot from 2020-08-24 18-23-56](https://user-images.githubusercontent.com/4147924/91071288-4a759b80-e638-11ea-9bfb-5aab284945c3.png)
![Screenshot from 2020-08-24 18-24-08](https://user-images.githubusercontent.com/4147924/91071289-4b0e3200-e638-11ea-90a2-3aa921aeb0a2.png)
![Screenshot from 2020-08-24 18-24-13](https://user-images.githubusercontent.com/4147924/91071290-4b0e3200-e638-11ea-8a82-f321229fb4f7.png)
![Screenshot from 2020-08-24 18-24-47](https://user-images.githubusercontent.com/4147924/91071292-4ba6c880-e638-11ea-8cea-064297f6f0c5.png)
![Screenshot from 2020-08-24 18-25-54](https://user-images.githubusercontent.com/4147924/91071295-4c3f5f00-e638-11ea-8497-242f75e15f61.png)
![Screenshot from 2020-08-24 18-25-59](https://user-images.githubusercontent.com/4147924/91071297-4cd7f580-e638-11ea-8896-08a9c55761dc.png)
![Screenshot from 2020-08-24 18-27-04](https://user-images.githubusercontent.com/4147924/91071299-4d708c00-e638-11ea-86e1-8584b1784b90.png)
![Screenshot from 2020-08-24 18-27-08](https://user-images.githubusercontent.com/4147924/91071301-4d708c00-e638-11ea-9e75-bc5cffcd3150.png)
![Screenshot from 2020-08-24 18-27-14](https://user-images.githubusercontent.com/4147924/91071302-4e092280-e638-11ea-8b9c-88958edabbe3.png)
![Screenshot from 2020-08-24 18-27-55](https://user-images.githubusercontent.com/4147924/91071304-4ea1b900-e638-11ea-9f5e-326534db5475.png)
![Screenshot from 2020-08-24 18-28-00](https://user-images.githubusercontent.com/4147924/91071305-4ea1b900-e638-11ea-8c35-77c632bccb64.png)
![Screenshot from 2020-08-24 18-28-42](https://user-images.githubusercontent.com/4147924/91071306-4f3a4f80-e638-11ea-91c9-8e9d1b4aa03a.png)
![Screenshot from 2020-08-24 18-29-19](https://user-images.githubusercontent.com/4147924/91071307-4fd2e600-e638-11ea-8a18-0d3c495ff533.png)
![Screenshot from 2020-08-24 18-29-22](https://user-images.githubusercontent.com/4147924/91071308-4fd2e600-e638-11ea-84a4-40eccc561e4d.png)
![Screenshot from 2020-08-24 18-29-25](https://user-images.githubusercontent.com/4147924/91071311-506b7c80-e638-11ea-84a5-603c8442bee3.png)
![Screenshot from 2020-08-24 18-29-40](https://user-images.githubusercontent.com/4147924/91071313-51041300-e638-11ea-8ad1-95ee78f27d9a.png)
![Screenshot from 2020-08-24 18-29-44](https://user-images.githubusercontent.com/4147924/91071316-51041300-e638-11ea-9f5e-91e4d98657f5.png)
![Screenshot from 2020-08-24 18-30-26](https://user-images.githubusercontent.com/4147924/91071319-519ca980-e638-11ea-8a99-ed4f1786b748.png)
![Screenshot from 2020-08-24 18-30-29](https://user-images.githubusercontent.com/4147924/91071320-519ca980-e638-11ea-83ab-86101789c704.png)
![Screenshot from 2020-08-24 18-30-35](https://user-images.githubusercontent.com/4147924/91071321-52354000-e638-11ea-9d13-d9c343eeba7f.png)
![Screenshot from 2020-08-24 18-30-40](https://user-images.githubusercontent.com/4147924/91071324-52cdd680-e638-11ea-871e-101fe3f50a4f.png)
![Screenshot from 2020-08-24 18-30-53](https://user-images.githubusercontent.com/4147924/91071325-52cdd680-e638-11ea-9a61-808290c9ffb0.png)
