### ISSUE TITLE
Earner Empathy map

### ISSUE THREAD

**Issue by MayElDardiry** [ANTS-COIN/platform#9]
![Empathy+Map+Cropped+centre](https://user-images.githubusercontent.com/25548635/90976429-4fa1f000-e53d-11ea-89a9-20b87b3997b5.jpg)

4 types of earners: 
	⁃	Beginner (no experience or knowledge)
	⁃	Intermediate (some knowledge)
	⁃	Expert (the experience in the user journey)

**Comment by NorhanZ** [comment]
Intermediate earner empathy map:
https://docs.google.com/document/d/1eYV1tXhD5lOuJLOKC_g3BeWKTioDMLoClr7decwjF-U/edit?usp=sharing

**Comment by NorhanZ** [comment]
Expert earner empathy map:
https://docs.google.com/document/d/1lvO8KEbFtl30HoRhWB0mI42FSXNZISDoHgL24rWnFRU/edit?usp=sharing
